name: CI

on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master

jobs:
  lint:
    name: Run lint tests
    runs-on: ubuntu-latest
    steps:
      # Check out the repo.
      - uses: actions/checkout@v2

      # Initiate caching for node_modules.
      - name: Cache node_modules
        uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}-${{ hashFiles('package.json') }}

      # Install the Yarn dependencies.
      - uses: actions/setup-node@v1
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install

      # Run the linting tests.
      - run: yarn lint
      - run: yarn prettier:check-all

  deploy:
    name: Deploy application to github.io
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}-${{ hashFiles('package.json') }}

      - uses: actions/setup-node@v1

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install

      - run: yarn build

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
